name: cloud-mariadb
icon: mariadb
type: db
title: Cloud MariaDB
external: true
options:
- version: 10.5
- version: 10.4
- version: 10.3
- version: 10.2
labels:
- mariadb
database:
  type: mariadb
  db: 
    name: '{{app.name}}_{{instance.name}}'    
    charset: 'utf8mb4'
    collation: 'utf8mb4_unicode_ci'    
  user:
    name: '{{app.name}}_{{instance.name}}'    
    password: '{{password}}'
tokens:
- name: password
  generate:
    regex: '[0-9a-z-]{32}'
